when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

liste_cultures:
    path: /cultures
    controller: App\Controller\ListeCulturesController::traitement
    methods:    GET

ajoute_culture:
    path: /culture/ajoute
    controller: App\Controller\AjouteCultureController::traitement
    methods:    POST

supprime_culture:
    path: /culture/supprime
    controller: App\Controller\SupprimeCultureController::traitement
    methods:    POST


